### PR TITLE
add 2nd template + route and sass + icons

### PR DESCRIPTION
**Pull request by afknapping**
- also larger example in readme

### CODE REVIEW

**Comment by afknapping** [comment]
mr @robin-drexler, PTAL

**Comment by robin-drexler** [comment]
UNICORNS! :D Looks pretty cool, just curious why you introduced a new route? The test is testing the other one. :D 

Since I dunno how to participate in this PR (because it's your repo and master branch?), I just merge and maybe schwurbel on some things later on.

**Comment by afknapping** [comment]
thx! :dancer: 

will remove the route, didn't get it at first.

you can give me push access or transfer ownership to jimdo org.

**Comment by robin-drexler** [comment]
Wanted to move it to jimdo org only if it reaches some sort of usable state. :D Will give you push access in a sec

**Pull request merged**
