### PR TITLE
WIP Styling

### PR DESCRIPTION
**Pull request by afknapping**
- also removed redundant route
- move visual stuff into theme file
- added parameter to load theme css file

### CODE REVIEW

**Comment by afknapping** [comment]
fund the failing test. but:

```
$ npm test

node.js:815
    var cwd = process.cwd();
                      ^
Error: ENOENT, no such file or directory
    at Function.startup.resolveArgv0 (node.js:815:23)
    at startup (node.js:58:13)
    at node.js:906:3

```

**Comment by afknapping** [comment]
some npm hickup. removed the failing test for now (text has become class and icon).

**Comment by afknapping** [comment]
merged the new tests but looks like i broke sth.

**Comment by afknapping** [comment]
merged master, kaputt-resolved conflicts in tests. `¯\_(ツ)_/¯`

**Comment by robin-drexler** [comment]
Merge this right now, so I can start with pdf generation (with styles already included).

Thaaaanks :)

**Pull request merged**
